jiraHost: ${{ secrets.JIRA_HOST }}
jiraEmail: ${{ secrets.JIRA_EMAIL }}
jiraToken: ${{ secrets.JIRA_TOKEN }}
jiraTicketRegex: (SFSVC-[0-9]+)
projectName: demohardis
developmentBranch: dodev
autoCleanTypes:
  - destructivechanges
  - flowPositions
  - minimizeProfiles
